apiVersion: v1
kind: Secret
metadata:
  name: mariadb
  labels:
    app: mywordpress
type: Opaque
data:
  password: test1234
  root_password: test1234
---
apiVersion: v1
kind: Secret
metadata:
  name: wordpress
  labels:
    app: mywordpress
type: Opaque
data:
  password: test1234
